name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-jet-module:
    name: Build JetModule
    runs-on: [ubuntu-latest-4-cores]
    steps:
      - name: Checkout JetModule
        uses: actions/checkout@v3
      - name: Configure JetModule
        run: |
          mkdir -p JetModule/build
          cd JetModule/build
          cmake -DCOMPILE_REFERENCE_APPLICATION=OFF ..
      - name: Build JetModule
        run: cd JetModule/build && make -j8