name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, ci/run-tests]
  workflow_dispatch:

jobs:
  build-jet-module:
    name: Build JetModule
    runs-on: [ubuntu-latest-4-cores]
    steps:
      - name: Checkout JetModule
        uses: actions/checkout@v3
      - name: Configure JetModule
        run: |
          mkdir -p build
          cd build
          cmake -DCOMPILE_REFERENCE_APPLICATION=OFF ..
      - name: Build JetModule
        run: cd build && make -j8
      - name: Print some info
        run: |
          echo $PWD
          ls -lh
      - name: Upload Shared Objects
        uses: actions/upload-artifact@v4
        with:
          name: so-files
          path: |
            build/bin/*.so
            build/tests/JetServerTest
            build/tests/PropertyConverterTest
  
  test-jet-module:
    name: Test JetModule
    needs: build-jet-module
    runs-on: [ubuntu-latest-4-cores]
    steps:
      - name: Download Shared Objects
        uses: actions/download-artifact@v4
        with:
          name: so-files
          path: |
            build/bin/*.so
            build/tests/JetServerTest
            build/tests/PropertyConverterTest
      - name: Print some info
        run: |
          echo $PWD
          ls -lh
          cd build
          ls -lh
          cd bin
          ls -lh
      - name: Run JetServerTest
        run: ./build/tests/JetServerTest
      - name: Run PropertyConverterTest
        run: ./build/tests/PropertyConverterTest
